namespace CrowdControl.Games.Packs.KH2FM;

public static class AbilityValues {
    public static int Slapshot = 0x6;
    public static int DodgeSlash = 0x7;
    public static int SlideDash = 0x8;
    public static int GuardBreak = 0x9;
    public static int Explosion = 0xA;
    public static int FinishingLeap = 0xB;
    public static int Counterguard = 0xC;
    public static int AerialSweep = 0xD;
    public static int AerialSpiral = 0xE;
    public static int HorizontalSlash = 0xF;
    public static int AerialFinish = 0x10;
    public static int RetaliatingSlash = 0x11;
    public static int ComboMaster = 0x1B;
    public static int DamageControl = 0x1E;
    public static int FlashStep = 0x2F;
    public static int AerialDive = 0x30;
    public static int MagnetBurst = 0x31;
    public static int VicinityBreak = 0x32;
    public static int DodgeRollLv1 = 0x34;
    public static int DodgeRollLv2 = 0x35;
    public static int DodgeRollLv3 = 0x36;
    public static int DodgeRollMax = 0x37;
    public static int AutoLimit = 0x38;
    public static int Guard = 0x52;
    public static int HighJumpLv1 = 0x5E;
    public static int HighJumpLv2 = 0x5F;
    public static int HighJumpLv3 = 0x60;
    public static int HighJumpMax = 0x61;
    public static int QuickRunLv1 = 0x62;
    public static int QuickRunLv2 = 0x63;
    public static int QuickRunLv3 = 0x64;
    public static int QuickRunMax = 0x65;
    public static int AerialDodgeLv1 = 0x66;
    public static int AerialDodgeLv2 = 0x67;
    public static int AerialDodgeLv3 = 0x68;
    public static int AerialDodgeMax = 0x69;
    public static int GlideLv1 = 0x6A;
    public static int GlideLv2 = 0x6B;
    public static int GlideLv3 = 0x6C;
    public static int GlideMax = 0x6D;
    public static int AutoValor = 0x81; // TODO Find out why the toggle value is different
    public static int SecondChance = 0x81; // TODO Find out why the toggle value is different
    public static int AutoWisdom = 0x82;
    public static int AutoMaster = 0x83;
    public static int AutoFinal = 0x84;
    public static int AutoSummon = 0x85;
    public static int ComboBoost = 0x86;
    public static int AirComboBoost = 0x87;
    public static int ReactionBoost = 0x88;
    public static int FinishingPlus = 0x89; // TODO Find out why the toggle value is different
    public static int UpperSlash = 0x89; // TODO Find out why the toggle value is different
    public static int NegativeCombo = 0x8A; // TODO Find out why the toggle value is different
    public static int Scan = 0x8A; // TODO Find out why the toggle value is different
    public static int BerserkCharge = 0x8B;
    public static int DamageDrive = 0x8C;
    public static int DriveBoost = 0x8D;
    public static int FormBoost = 0x8E;
    public static int SummonBoost = 0x8F;
    public static int CombinationBoost = 0x90;
    public static int ExperienceBoost = 0x91;
    public static int LeafBracer = 0x92;
    public static int MagicLockOn = 0x93;
    public static int NoExperience = 0x94;
    public static int Draw = 0x95;
    public static int Jackpot = 0x96;
    public static int LuckyLucky = 0x97;
    public static int DriveConverter = 0x98;
    public static int FireBoost = 0x98;
    public static int BlizzardBoost = 0x99;
    public static int ThunderBoost = 0x9A;
    public static int ItemBoost = 0x9B;
    public static int MPRage = 0x9C;
    public static int MPHaste = 0x9D;
    public static int MPHastega = 0x9E; // TODO Find out why the toggle value is different
    public static int AerialRecovery = 0x9E; // TODO Find out why the toggle value is different
    public static int Defender = 0x9E; // TODO Find out why the toggle value is different
    public static int OnceMore = 0xA0;
    public static int ComboPlus = 0xA2; // TODO Find out why the toggle value is different
    public static int AutoChange = 0xA2; // TODO Find out why the toggle value is different
    public static int AirComboPlus = 0xA3; // TODO Find out why the toggle value is different
    public static int HyperHealing = 0xA3; // TODO Find out why the toggle value is different
    public static int AutoHealing = 0xA4;
    public static int MPHastera = 0xA5; // TODO Find out why the toggle value is different
    public static int DonaldFire = 0xA5; // TODO Find out why the toggle value is different
    public static int DonaldBlizzard = 0xA6;
    public static int DonaldThunder = 0xA7; // TODO Find out why the toggle value is different
    public static int GoofyTornado = 0xA7; // TODO Find out why the toggle value is different
    public static int DonaldCure = 0xA8;
    public static int GoofyTurbo = 0xA9;
    public static int SlashFrenzy = 0xAA;
    public static int Quickplay = 0xAB;
    public static int Divider = 0xAC;
    public static int GoofyBash = 0xAD;
    public static int FerociousRush = 0xAE;
    public static int BlazingFury = 0xAF;
    public static int IcyTerror = 0xB0; // TODO Find out why the toggle value is different
    public static int HealingWater = 0xB0; // TODO Find out why the toggle value is different
    public static int BoltsOfSorrow = 0xB1; // TODO Find out why the toggle value is different
    public static int FuriousShout = 0xB1; // TODO Find out why the toggle value is different
    public static int MushuFire = 0xB2;
    public static int Flametongue = 0xB3;
    public static int DarkShield = 0xB4;
    public static int Groundshaker = 0xB6; // TODO Find out why the toggle value is different
    public static int DarkAura = 0xB6; // TODO Find out why the toggle value is different
    public static int FierceClaw = 0xB7;
    public static int CurePotion = 0xBB;
    public static int ScoutingDisk = 0xBC;
    public static int HealingHerb = 0xBE; // TODO Find out why the toggle value is different
    public static int NoMercy = 0xBE; // TODO Find out why the toggle value is different
    public static int RainStorm = 0xBF;
    public static int BoneSmash = 0xC0;
    public static int TrinityLimit = 0xC6;
    public static int Fantasia = 0xC7;
    public static int FlareForce = 0xC8;
    public static int TornadoFusion = 0xC9;
    public static int TrickFantasy = 0xCB;
    public static int Overdrive = 0xCC;
    public static int HowlingMoon = 0xCD;
    public static int AplauseAplause = 0xCE;
    public static int Dragonblaze = 0xCF;
    public static int Teamwork = 0xCA;
    public static int EternalSession = 0xD0;
    public static int KingsPride = 0xD1;
    public static int TreasureIsle = 0xD2;
    public static int CompleteCompilment = 0xD3;
    public static int PulsingThunder = 0xD7;

    public static int SoraAbilityCount = 148;
    public static int DonaldAbilityCount = 34;
    public static int GoofyAbilityCount = 34;
    public static int MulanAbilityCount = 16;
    public static int BeastAbilityCount = 16;
    public static int AuronAbilityCount = 14;
    public static int CaptainJackSparrowAbilityCount = 24;
    public static int AladdinAbilityCount = 18;
    public static int JackSkellingtonAbilityCount = 22;
    public static int SimbaAbilityCount = 18;
    public static int TronAbilityCount = 18;
    public static int RikuAbilityCount = 22;
}